"""Resolve plugin-contributed rules into one agent-readable document."""

from __future__ import annotations

import os
import tempfile
from collections.abc import Iterable
from pathlib import Path

from .registry import (
    AgentRuleDefinition,
    ModuleRegistry,
    WorkflowDefinition,
    build_module_registry,
    build_workflow_registry,
)

PROJECT_AGENT_RULES_PATH = Path("docs") / "agent-rules.md"
EFFECTIVE_AGENT_RULES_ROOT = Path(".electroboy") / "local" / "agent-rules"


def resolve_agent_rules(
    modules: ModuleRegistry,
    workflow: WorkflowDefinition,
) -> tuple[AgentRuleDefinition, ...]:
    """Return ordered rules contributed by a workflow and its modules."""

    rules = [
        rule
        for module_id in workflow.modules
        for rule in modules.get(module_id).agent_rules
    ]
    rules.extend(workflow.agent_rules)
    identifiers = [rule.id for rule in rules]
    duplicate_ids = sorted(
        identifier
        for identifier in set(identifiers)
        if identifiers.count(identifier) > 1
    )
    if duplicate_ids:
        raise ValueError(
            "duplicate resolved agent rule identifiers: "
            + ", ".join(duplicate_ids)
        )
    return tuple(sorted(rules, key=lambda rule: (rule.priority, rule.id)))


def render_agent_rules(
    workflow: WorkflowDefinition,
    rules: Iterable[AgentRuleDefinition],
    project_rules: str | None = None,
) -> str:
    """Render an effective rules document for one workflow."""

    lines = [
        f"# {workflow.label} Agent Rules",
        "",
        "This file is generated by ElectroBoy for every agent in this workflow.",
        "Read the applicable sections before creating, naming, or modifying a",
        "document. Rules marked as required override recommendations. Explicit",
        "operator instructions override naming recommendations.",
        f"Project additions may be placed in `{PROJECT_AGENT_RULES_PATH.as_posix()}`.",
    ]
    for rule in rules:
        lines.extend(
            [
                "",
                f"## {rule.label}",
                "",
                rule.content.strip(),
            ]
        )
    if project_rules and project_rules.strip():
        lines.extend(
            [
                "",
                "## Project Rules",
                "",
                f"Loaded from `{PROJECT_AGENT_RULES_PATH.as_posix()}`.",
                "",
                project_rules.strip(),
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def materialize_workflow_agent_rules(
    root: Path,
    workflow_id: str,
) -> str:
    """Write the effective rules and return its project-relative path."""

    project_root = root.expanduser().resolve()
    modules = build_module_registry()
    workflows = build_workflow_registry(modules)
    workflow = workflows.get(workflow_id)
    rules = resolve_agent_rules(modules, workflow)
    project_rules_path = project_root / PROJECT_AGENT_RULES_PATH
    project_rules = (
        project_rules_path.read_text(encoding="utf-8")
        if project_rules_path.is_file()
        else None
    )
    content = render_agent_rules(workflow, rules, project_rules)
    destination = project_root / EFFECTIVE_AGENT_RULES_ROOT / f"{workflow.id}.md"
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.is_file() and destination.read_text(encoding="utf-8") == content:
        return destination.relative_to(project_root).as_posix()

    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary_path = Path(temporary.name)
        os.replace(temporary_path, destination)
        temporary_path = None
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
    return destination.relative_to(project_root).as_posix()
